---
- hosts: control
  strategy: free
  gather_facts: false
  become: true
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname control.example.com
  - name: Creating Ansible User
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Fixing Resolv File
    shell: echo 'nameserver 8.8.8.8' > /etc/resolv.conf
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding localhost IPV4 address to host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding localhost IPV6 address to host file
    lineinfile:
      path: /etc/hosts
      line: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      create: yes
  - name: Adding repo address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.199 repo.example.com repo
      create: yes
  - name: Adding Control address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.200 control.example.com control
      create: yes
  - name: Adding node1 address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.201 node1.example.com node1
      create: yes
  - name: Adding node2 address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.202 node2.example.com node2
      create: yes
  - name: Adding node3 address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.203 node3.example.com node3
      create: yes
#  - name: Adding node4 address to hosts file
#    lineinfile:
#      path: /etc/hosts
#      line: 192.168.55.204 node4.example.com node4
#      create: yes
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/ipa.repo
      block: |
       [base]
       name=Base
       baseurl=http://repo/BaseOS
       gpgcheck=0
       enabled=1
       
       [apps]
       name=Apps
       baseurl=http://repo/AppStream
       gpgcheck=0
       enabled=1
    tags: repo
  - name: Enabling services
    shell: for i in firewalld httpd ; do systemctl enable --now $i;done
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloading Firewall
    command: firewall-cmd --reload
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.200/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search example.com ipv4.method manual
  - name: Reloaded Network.
    shell: nmcli con up "System eth1"
  - name: Generating RSA Key
    command : ssh-keygen -q -t rsa -f /home/user/.ssh/id_rsa -C "" -N ""
    become: yes
    become_user: user
  - name: Disabling services
    selinux:
      state: disabled
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
        #!/bin/bash
        #
        echo -e '       
        #            _            _           _          _           _          _           _     
        #          /\ \          /\ \        /\ \     _ /\ \        /\ \       /\ \        _\ \   
        #         /  \ \        /  \ \      /  \ \   /\_\_\ \      /  \ \     /  \ \      /\__ \  
        #        / /\ \ \      / /\ \ \    / /\ \ \_/ / /\__ \    / /\ \ \   / /\ \ \    / /_ \_\ 
        #       / / /\ \ \    / / /\ \ \  / / /\ \___/ / /_ \ \  / / /\ \_\ / / /\ \ \  / / /\/_/ 
        #      / / /  \ \_\  / / /  \ \_\/ / /  \/____/ / /\ \ \/ / /_/ / // / /  \ \_\/ / /      
        #     / / /    \/_/ / / /   / / / / /    / / / / /  \/_/ / /__\/ // / /   / / / / /       
        #    / / /         / / /   / / / / /    / / / / /     / / /_____// / /   / / / / / ____   
        #   / / /________ / / /___/ / / / /    / / / / /     / / /\ \ \ / / /___/ / / /_/_/ ___/\ 
        #  / / /_________/ / /____\/ / / /    / / /_/ /     / / /  \ \ / / /____\/ /_______/\__\/ 
        #  \/____________\/_________/\/_/     \/_/\_\/      \/_/    \_\\/_________/\_______\/     
        '"#
        #
        # You are logged into \"`hostname`\" as user \"`whoami`\"
        # This system is running `cat /etc/redhat-release`
        # kernel is `uname -r`
        #
        #
        # Repo/AppStream 
        # Available to use from http://repo.example.com/BaseOS and http://repo.example.com/AppStream
        "