---
- name: Sending SSH Keys to Nodes
  hosts: control
  become: true
  ignore_errors: yes
  tasks: 
  - name: Sending Key to node1
    expect:
      command: ssh-copy-id -i /home/user/.ssh/id_rsa.pub user@node1.ansi.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'password'
      timeout: 10
    become_user: user
  - name: Sending Key to node2
    expect:
      command: ssh-copy-id -i /home/user/.ssh/id_rsa.pub user@node2.ansi.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'password'
      timeout: 10
    become_user: user
  - name: Sending Key to node3
    expect:
      command: ssh-copy-id -i /home/user/.ssh/id_rsa.pub user@node3.ansi.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'password'
      timeout: 10
    become_user: user
  - name: Sending Key to node4
    expect:
      command: ssh-copy-id -i /home/user/.ssh/id_rsa.pub user@node4.ansi.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'password': 'password'
      timeout: 10
    become_user: user
  - name: Welcome to the RHCE 8 Study/Test Environment!
    debug:
      msg:
        - 'Next Steps: Accessing The Systems:'
        - '- Control - 192.168.55.200'
        - '- Node 1 - 192.168.55.201'
        - '- Node 2 - 192.168.55.202'
        - '- Node 3 - 192.168.55.203'
        - '- Node 4 - 192.168.55.204'
        - '- Username/Password - user/password'
        - '--------------------------------------------------'
        - '- For root - use `sudo` or `sudo su`'
        - '- Access example - ssh user@192.168.55.200'
        - '- Happy Studying!'
        
...